name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-config: |
          Host lim115.truehost.cloud
            Port 1624

    - name: Sync files to server
      run: |
        rsync -avz --exclude='.git*' --exclude='node_modules' --delete ./ osjoqorl@branighangroup.com:/home/osjoqorl/public_html
